### ISSUE TITLE
format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long int’ [-Wformat=]

### ISSUE THREAD

**Issue by runeksvendsen** [jberthold/packman#17]
I'm trying to build using gcc 12.2.0 on macOS 13.6.7 and I get the error below.

Which version(s) of gcc has been used to successfully compile this package?

```
cbits/Pack.c: In function ‘UnpackClosure’:

/Users/rune/code/packman/cbits/Pack.c:2037:20: error:
     warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long int’ [-Wformat=]
     2037 |         errorBelch("unpackClosure: Found invalid marker %" FMT_Word ".\n",
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2038 |                    (long) **bufptrP);
          |                    ~~~~~~~~~~~~~~~~
          |                    |
          |                    long int
     |
2037 |         errorBelch("unpackClosure: Found invalid marker %" FMT_Word ".\n",
     |                    ^
In file included from /Users/rune/.stack/programs/x86_64-osx/ghc-8.6.5/lib/ghc-8.6.5/include/stg/Types.h:37,
                 from /Users/rune/.stack/programs/x86_64-osx/ghc-8.6.5/lib/ghc-8.6.5/include/Stg.h:222,
                 from /Users/rune/.stack/programs/x86_64-osx/ghc-8.6.5/lib/ghc-8.6.5/include/Rts.h:29,

/Users/rune/code/packman/                 from cbits/Pack.c:24:0: error:

/Users/rune/code/packman//nix/store/c834w8pg8ypl9lcaxqgj2bpsxbv518rn-Libsystem-1238.60.2/include/inttypes.h:64:53: error:
     note: format string is defined here
       64 | #  define PRIu64        __PRI_64_LENGTH_MODIFIER__ "u"
   |
64 | #  define PRIu64        __PRI_64_LENGTH_MODIFIER__ "u"
   |                                                     ^
/nix/store/dhyy4g59fchi4sb5sgmbxf5h3lb1hdbq-cctools-port-973.0.1/libexec/as/x86_64/as: this system assembler is deprecated. Please migrate to the clang integrated assembler (`as -q').
cbits/Pack.c: In function ‘UnpackClosure’:

/Users/rune/code/packman/cbits/Pack.c:2037:20: error:
     warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long int’ [-Wformat=]
     2037 |         errorBelch("unpackClosure: Found invalid marker %" FMT_Word ".\n",
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2038 |                    (long) **bufptrP);
          |                    ~~~~~~~~~~~~~~~~
          |                    |
          |                    long int
     |
2037 |         errorBelch("unpackClosure: Found invalid marker %" FMT_Word ".\n",
     |                    ^
In file included from /Users/rune/.stack/programs/x86_64-osx/ghc-8.6.5/lib/ghc-8.6.5/include/stg/Types.h:37,
                 from /Users/rune/.stack/programs/x86_64-osx/ghc-8.6.5/lib/ghc-8.6.5/include/Stg.h:222,
                 from /Users/rune/.stack/programs/x86_64-osx/ghc-8.6.5/lib/ghc-8.6.5/include/Rts.h:29,

/Users/rune/code/packman/                 from cbits/Pack.c:24:0: error:

/Users/rune/code/packman//nix/store/c834w8pg8ypl9lcaxqgj2bpsxbv518rn-Libsystem-1238.60.2/include/inttypes.h:64:53: error:
     note: format string is defined here
       64 | #  define PRIu64        __PRI_64_LENGTH_MODIFIER__ "u"
   |
64 | #  define PRIu64        __PRI_64_LENGTH_MODIFIER__ "u"
   |                                                     ^
/nix/store/dhyy4g59fchi4sb5sgmbxf5h3lb1hdbq-cctools-port-973.0.1/libexec/as/x86_64/as: this system assembler is deprecated. Please migrate to the clang integrated assembler (`as -q').
/nix/store/dhyy4g59fchi4sb5sgmbxf5h3lb1hdbq-cctools-port-973.0.1/libexec/as/x86_64/as: this system assembler is deprecated. Please migrate to the clang integrated assembler (`as -q').
/nix/store/dhyy4g59fchi4sb5sgmbxf5h3lb1hdbq-cctools-port-973.0.1/libexec/as/x86_64/as: this system assembler is deprecated. Please migrate to the clang integrated assembler (`as -q').
ld: warning: dylib (/Users/rune/.stack/snapshots/x86_64-osx/9ef72302989af47487b78cff7946ca6168e3c5b45dd9a038a748bec03ffdc9b5/8.6.5/lib/x86_64-osx-ghc-8.6.5/libHSprimitive-0.6.4.0-ILgywxtLpvnAOlEISPpP5b-ghc8.6.5.dylib) was built for newer macOS version (12.0) than being linked (10.12)
packman> copy/register
Installing library in /Users/rune/code/packman/.stack-work/install/x86_64-osx/dd344f5d328467b9444c81fee1b833bf8c7ca451762711a082f43488b1cb2b01/8.6.5/lib/x86_64-osx-ghc-8.6.5/packman-0.5.1-1IGskA4e7zb86d6Vzbb8Jc
Registering library for packman-0.5.1..
```

**Comment by runeksvendsen** [comment]
> Which version(s) of gcc has been used to successfully compile this package?

I tried with GCC 9.5.0 and it works.

**Comment by runeksvendsen** [comment]
It looks like this is only a warning, given that I see tests passing after seeing the above in the logs, even though it says e.g.

```
/Users/rune/code/packman/cbits/Pack.c:2037:20: error:
```

So I'm closing this issue.
